name: wave-infografic
channels:
  - conda-forge
dependencies:
  - ipywidgets=7.5.1
  - bqplot
  - voila=0.1.12
  - ipyleaflet=0.11.4
#   - scipy
#   - rasterio
#   - tqdm
#   - requests
#   - pillow
#   - matplotlib
#   - flask
#   - branca
#   - geopandas
#   - netcdf4